# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 943c8826b5bf1dfc50a9c059d1f77098896aecc7066e334ad96fde95d94750cf4d412b54518ab3f84e9d2726863dffa6baedc78749dce084f2e9a5e8fbc2efb8

test:
  secret_key_base: dab237273f9210872aa0ee1c57bb235c8b5fd86d900fbb47526611ec73ce34cdc44bd54e36b8a76edd9d4604d22e342c1f755a3fcbbe09f91f4514e7f7616bd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
